### ISSUE TITLE
Error Running mod on dedicated server.

### ISSUE THREAD

**Issue by dankmaster** [searica/NetworkTweaks#2]
Nothing sync, and im also getting this error on the client side.
[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <31687ccd371e4dc6b0c23a1317cf9474>:0)
NetworkTweaks.Patches.ZDOToPeersPatches.SendZDOToPeers (ZDOMan zdoManager, System.Single dt) (at <12c03e9be6cf4a09958824118e03b6ba>:0)
(wrapper dynamic-method) ZDOMan.DMD<ZDOMan::Update>(ZDOMan,single)
ZNet.Update () (at <889b2bc1e1224b249a4784da9ef107e2>:0)

**Comment by searica** [comment]
Could you share a full log file using the most recent version of NetworkTweaks?

**Comment by dankmaster** [comment]
sure thing boss.
[LogOutput.log](https://github.com/user-attachments/files/18264006/LogOutput.log)

**Comment by searica** [comment]
All right, please try again with v0.1.4 which has just been pushed to this repo. You can use the dll or import the zip using a mod manager. I've uploaded it to Thunderstore already but it can take an hour or two to show up for downloading there.

Link: https://github.com/searica/NetworkTweaks/tree/main/Publish/ThunderStore

Turns out the base game initializes one of their counters to -1 rather than 0 as the default value. Didn't expect that so it was triggering an out of range exception. Thanks for reporting the issue!

**Comment by dankmaster** [comment]
Yep, that did it! Thanks for quick fix, will try it further :D
Since it's more like peer-to-peer now, i guess Serverside Simulations is redudant now?

**Comment by searica** [comment]
I'm not familiar with any mod called `Serrverside Simulations`, so I can't say. In general though, if you think a central server can run everything faster than the a distributed peer network then running the bulk of computations on the server can still be of benefit. Similarly, a central server can help with peers that are very far apart and have poor connections if the server is located between those peers. Alternatively, if the central server is not computationally stronger than the distributed peer network and the peers all have good connections to each other then you may not see any benefits from a central server.

**Comment by dankmaster** [comment]
Thanks for the reply bro, the plugin is working fine with 3 players.
